// utils/ghana-regions-districts.ts

/**
 * Ghana Regions & Districts
 * Source: MLGRD / GSS (2021 demarcations)
 */

export const REGIONS: string[] = [
  "Ahafo",
  "Ashanti",
  "Bono",
  "Bono East",
  "Central",
  "Eastern",
  "Greater Accra",
  "North East",
  "Northern",
  "Oti",
  "Savannah",
  "Upper East",
  "Upper West",
  "Volta",
  "Western",
  "Western North",
];

const DISTRICTS: Record<string, string[]> = {
  Ahafo: [
    "Asunafo North",
    "Asunafo South",
    "Asutifi North",
    "Asutifi South",
    "Tano North",
    "Tano South",
  ],
  Ashanti: [
    "Adansi Asokwa",
    "Adansi North",
    "Adansi South",
    "Afigya Kwabre North",
    "Afigya Kwabre South",
    "Ahafo Ano North",
    "Ahafo Ano South East",
    "Ahafo Ano South West",
    "Amansie Central",
    "Amansie South",
    "Amansie West",
    "Asante Akim Central",
    "Asante Akim North",
    "Asante Akim South",
    "Asokore Mampong",
    "Atwima Kwanwoma",
    "Atwima Mponua",
    "Atwima Nwabiagya North",
    "Atwima Nwabiagya South",
    "Bekwai",
    "Bosome Freho",
    "Bosomtwe",
    "Ejisu",
    "Ejura Sekyedumase",
    "Juaben",
    "Kumasi Metropolitan",
    "Kwabre East",
    "Mampong",
    "Obuasi East",
    "Obuasi Municipal",
    "Offinso Municipal",
    "Offinso North",
    "Oforikrom",
    "Old Tafo",
    "Sekyere Afram Plains",
    "Sekyere Central",
    "Sekyere East",
    "Sekyere Kumawu",
    "Sekyere South",
    "Suame",
  ],
  Bono: [
    "Banda",
    "Berekum East",
    "Berekum West",
    "Dormaa Central",
    "Dormaa East",
    "Dormaa West",
    "Jaman North",
    "Jaman South",
    "Sunyani Municipal",
    "Sunyani West",
    "Tain",
    "Wenchi",
  ],
  "Bono East": [
    "Atebubu-Amantin",
    "Kintampo North",
    "Kintampo South",
    "Nkoranza North",
    "Nkoranza South",
    "Pru East",
    "Pru West",
    "Sene East",
    "Sene West",
    "Techiman Municipal",
    "Techiman North",
  ],
  Central: [
    "Abura Asebu Kwamankese",
    "Agona East",
    "Agona West",
    "Ajumako Enyan Essiam",
    "Asikuma Odoben Brakwa",
    "Assin Central",
    "Assin North",
    "Assin South",
    "Awutu Senya",
    "Awutu Senya East",
    "Cape Coast Metropolitan",
    "Effutu",
    "Ekumfi",
    "Gomoa East",
    "Gomoa Central",
    "Gomoa West",
    "Komenda-Edina-Eguafo-Abirem",
    "Mfantsiman",
    "Twifo Atti-Morkwa",
    "Twifo-Hemang-Lower Denkyira",
    "Upper Denkyira East",
    "Upper Denkyira West",
  ],
  Eastern: [
    "Abuakwa North",
    "Abuakwa South",
    "Achiase",
    "Akuapem North",
    "Akuapem South",
    "Akyemansa",
    "Asuogyaman",
    "Atiwa East",
    "Atiwa West",
    "Ayensuano",
    "Birim Central",
    "Birim North",
    "Birim South",
    "Denkyembour",
    "Fanteakwa North",
    "Fanteakwa South",
    "Kwaebibirem",
    "Kwahu Afram Plains North",
    "Kwahu Afram Plains South",
    "Kwahu East",
    "Kwahu South",
    "Kwahu West",
    "Lower Manya Krobo",
    "New Juaben North",
    "New Juaben South",
    "Nsawam Adoagyiri",
    "Okere",
    "Suhum",
    "Upper Manya Krobo",
    "Upper West Akim",
    "West Akim",
    "Yilo Krobo",
  ],
  "Greater Accra": [
    "Ablekuma Central",
    "Ablekuma North",
    "Ablekuma West",
    "Accra Metropolitan",
    "Ada East",
    "Ada West",
    "Adenta",
    "Ashaiman",
    "Ayawaso Central",
    "Ayawaso East",
    "Ayawaso North",
    "Ayawaso West",
    "Ga Central",
    "Ga East",
    "Ga North",
    "Ga South",
    "Ga West",
    "Korle Klottey",
    "Kpone Katamanso",
    "Krowor",
    "La Dade-Kotopon",
    "La Nkwantanang-Madina",
    "Ledzokuku",
    "Ningo Prampram",
    "Okaikwei North",
    "Shai Osudoku",
    "Tema Metropolitan",
    "Tema West",
    "Weija Gbawe",
  ],
  "North East": [
    "Bunkpurugu-Nyakpanduri",
    "Chereponi",
    "East Mamprusi",
    "Mamprugu Moagduri",
    "West Mamprusi",
    "Yunyoo-Nasuan",
  ],
  Northern: [
    "Gushegu",
    "Karaga",
    "Kpandai",
    "Kumbungu",
    "Mion",
    "Nanton",
    "Nanumba North",
    "Nanumba South",
    "Saboba",
    "Sagnarigu",
    "Savelugu",
    "Tamale Metropolitan",
    "Tatale-Sangule",
    "Tolon",
    "Yendi",
    "Zabzugu",
  ],
  Oti: [
    "Biakoye",
    "Jasikan",
    "Kadjebi",
    "Krachi East",
    "Krachi Nchumuru",
    "Krachi West",
    "Nkwanta North",
    "Nkwanta South",
  ],
  Savannah: [
    "Bole",
    "Central Gonja",
    "East Gonja",
    "North East Gonja",
    "North Gonja",
    "Sawla-Tuna-Kalba",
    "West Gonja",
  ],
  "Upper East": [
    "Bawku Municipal",
    "Bawku West",
    "Binduri",
    "Bolgatanga East",
    "Bolgatanga Municipal",
    "Bongo",
    "Builsa North",
    "Builsa South",
    "Garu",
    "Kassena Nankana Municipal",
    "Kassena Nankana West",
    "Nabdam",
    "Pusiga",
    "Talensi",
    "Tempane",
  ],
  "Upper West": [
    "Daffiama Bussie Issa",
    "Jirapa",
    "Lambussie",
    "Lawra",
    "Nadowli-Kaleo",
    "Nandom",
    "Sissala East",
    "Sissala West",
    "Wa East",
    "Wa Municipal",
    "Wa West",
  ],
  Volta: [
    "Adaklu",
    "Afadjato South",
    "Agotime Ziope",
    "Akatsi North",
    "Akatsi South",
    "Anloga",
    "Central Tongu",
    "Ho Municipal",
    "Ho West",
    "Hohoe Municipal",
    "Keta Municipal",
    "Ketu North",
    "Ketu South",
    "Kpando Municipal",
    "North Dayi",
    "North Tongu",
    "South Dayi",
    "South Tongu",
  ],
  Western: [
    "Ahanta West",
    "Effia Kwesimintsim",
    "Ellembelle",
    "Jomoro",
    "Mpohor",
    "Nzema East",
    "Prestea-Huni Valley",
    "Sekondi-Takoradi",
    "Shama",
    "Tarkwa-Nsuaem",
    "Wassa Amenfi Central",
    "Wassa Amenfi East",
    "Wassa Amenfi West",
    "Wassa East",
  ],
  "Western North": [
    "Aowin",
    "Bia East",
    "Bia West",
    "Bibiani Anhwiaso Bekwai",
    "Juaboso",
    "Sefwi Akontombra",
    "Sefwi Wiawso",
    "Suaman",
  ],
};

/** Return all regions */
export const getAllRegions = (): string[] => REGIONS;

/** Return districts by region */
export const getDistrictsByRegion = (region: string): string[] => {
  return DISTRICTS[region] ?? [];
};
