import { images } from "@/constants/images";
import { Request } from "@/types/request";

export const sampleRequests: Request[] = [
  {
    id: 1,
    serviceType: "Tractor",
    serviceDetails: "Ripping Land Preparation & Soil Breaking",
    farmLocation: "Ejisu Adadientem, Kumasi",
    providerName: "P. Akwasi",
    dateRequested: "August 2, 2025",
    status: "ongoing",
    progress: 0.7,
    daysLeft: 29,
    asset: {
      machineType: "Tractor",
      machineName: "Big Akwasi",
      status: "Active",
      farmerName: "F. Sarfo Kofi",
      task: "Ripping Land Preparation & Soil Breaking",
      dateLeft: "29 Days left",
      image: images.tractor1,
    },
  },
  {
    id: 2,
    serviceType: "Harvester",
    serviceDetails: "Harvesting Maize Field",
    farmLocation: "Abrepo, Kumasi",
    providerName: "P. Kofi",
    dateRequested: "August 3, 2025",
    status: "completed",
    dateCompleted: "September 21, 2025",
    asset: {
      machineType: "Harvester",
      machineName: "Nsiah Afui",
      status: "Inactive",
      farmerName: "F. Yaw Mensah",
      task: "Harvesting Maize Field",
      dateLeft: "14 Days left",
      image: images.tractor2,
    },
  },
  {
    id: 3,
    serviceType: "Drone",
    serviceDetails: "Aerial Spraying & Monitoring",
    farmLocation: "Bantama, Kumasi",
    providerName: "P. Akwasi",
    dateRequested: "August 4, 2025",
    status: "cancelled",
    cancelledBy: "admin",
  },
  {
    id: 4,
    serviceType: "Irrigation",
    serviceDetails: "Drip Installation Assessment",
    farmLocation: "KNUST Campus",
    providerName: "P. Provider Ltd.",
    dateRequested: "August 5, 2025",
    status: "cancelled",
    cancelledBy: "farmer",
  },
  {
    id: 5,
    serviceType: "Planting",
    serviceDetails: "Drip Installation Assessment",
    farmLocation: "KNUST Campus",
    providerName: "P. Provider Ltd.",
    dateRequested: "August 5, 2025",
    status: "sent",
  },
  {
    id: 6,
    serviceType: "Irrigation",
    serviceDetails: "Drip Installation Assessment",
    farmLocation: "KNUST Campus",
    providerName: "P. Provider Ltd.",
    dateRequested: "August 5, 2025",
    status: "sent",
  },
];
